<div class="panel">
    <div class="panel-heading">
        <h1 class="page-header">O projektu</h1>
    </div>
    <div class="panel-body">
        <p>Projekt je vytvořen předev&scaron;&iacute;m pro studenty ZČU FAV, za &uacute;čelem shrom&aacute;ždit co nejv&iacute;ce informac&iacute; o programov&aacute;n&iacute; na jedno m&iacute;sto bez ž&aacute;dn&eacute;ho omezov&aacute;n&iacute;.</p>
    </div>
    <div class="panel-footer"></div>
</div>