<div class="panel">
    <div class="panel-heading">
        <h1 class="page-header">Archiv článků</h1>
    </div>
    <div class="panel-body">
        <? if ($articles) : ?>
            <div class="row articles isotope-grid">
            <? foreach ($articles as $article) : ?>
                <?= (new \app\model\snippet\ArticleIndexSnippet($article))->render() ?>
            <? endforeach?>
            </div>
        <? else : ?>
            <div class="col-md-8">Nebyly nalezeny žádné schválené články</div>
        <? endif ?>
    </div>
    <div class="panel-footer">
        <span class="btn btn-xs btn-primary load-next" data-page="2">Načíst další</span>
    </div>
</div>

<script type="text/javascript" src="js/manager/articleManager.js"></script>
<script>
    var downloading = false;
    var articleManager = new ArticleManager();

    jQuery(document).ready(function () {

        jQuery(".load-next").click(function () {
            var self = $(this);
            var id = self.data("page");
            articleManager.getNext(id, function (data) {
                var articles = jQuery(".articles");
                for (var i = 0; i < data.length; i++) {
                    articles.isotope("insert", $(data[i]));
                }
                self.data("page", ++id);
            });
        });
    });
</script>