<form method="post">
    <div class="panel">
        <div class="panel-heading">
            <h1 class="page-header">Editor článku</h1>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="form-group">
                        <label class="control-label" for="article-title">Titulek článku:</label>
                        <input id="article-title" class="form-control input-md" name="article_title" type="text"
                               placeholder="titulek článku" value="<?= $article['article_title'] ?>">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="article-category">Kategorie článku:</label>
                        <select id="article-category" name="article_category" class="form-control">
                            <? if (isset($articleCategory)): ?>
                                <option
                                    value="<?= $articleCategory->getID() ?>"><?= $articleCategory->getName() ?></option>
                            <? else : ?>
                                <option value="-1">Vyberte...</option>
                            <? endif ?>
                            <? //@var array $categories
                            foreach ($categories as $category) : ?>
                                <option
                                    value="<?= $category['category_id']; ?>"><?= $category['category_name']; ?></option>
                            <? endforeach ?>
                        </select>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="form-group">
                        <label class="control-label" for="article-description">Popis článku:</label>
                        <input id="article-description" name="article_description" type="text"
                               placeholder="popis článku"
                               class="form-control input-md"
                               required="" value="<?= $article['article_description'] ?>">
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="article-tags">Vyhledávací tagy:</label>
                        <input id="article-tags" name="article_tags" type="text" placeholder="vyhledávací tagy"
                               class="form-control input-md"
                               required="" value="<?= $article['article_tags'] ?>">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="form-group">
                        <label class="control-label" for="article-previous">Předchozí článek:</label>
                        <select id="article-previous" name="article_previous" class="form-control">
                            <? if (isset($articlePrev)) : ?>
                                <option value="<?= $articlePrev->getID() ?>"><?= $articlePrev->getTitle() ?></option>
                            <? else : ?>
                                <option value="-1">Vyberte...</option>
                            <? endif ?>
                            <? if (isset($articles)) : ?>
                                <? foreach ($articles as $art) : ?>
                                    <option value="<?= $art['article_id'] ?>"><?= $art['article_title'] ?></option>
                                <? endforeach ?>
                            <? endif ?>
                            <? if (isset($articlePrev)) : ?>
                                <option value="-1">Vyberte...</option>
                            <? endif ?>
                        </select>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="form-group">
                        <label class="control-label" for="article-next">Další článek:</label>
                        <select id="article-next" name="article_next" class="form-control">
                            <? if (isset($articleNext)) : ?>
                                <option value="<?= $articleNext->getID() ?>"><?= $articleNext->getTitle() ?></option>
                            <? else : ?>
                                <option value="-1">Vyberte...</option>
                            <? endif ?>
                            <? if (isset($articles)) : ?>
                                <? foreach ($articles as $art) : ?>
                                    <option value="<?= $art['article_id'] ?>"><?= $art['article_title'] ?></option>
                                <? endforeach ?>
                            <? endif ?>
                            <? if (isset($articleNext)) : ?>
                                <option value="-1">Vyberte...</option>
                            <? endif ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div id="mainEditorContainer"></div>
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" class="btn btn-xs btn-primary"
                   value="<?= ($artAction == 'new') ? 'Vytvořit' : 'Upravit' ?>">
            <a href="article-manager" class="btn btn-xs btn-warning right">Zrušit</a>
        </div>
    </div>
</form>
<script src="js/editorJQ.js"></script>
<script src="js/view/article-editor.js"></script>