<form method="post" class="form-horizontal">
<div class="panel">
    <div class="panel-heading">
        <h1 class="panel-title">Aktivace účtu</h1>
    </div>
    <div class="panel-body">
            <fieldset>
                <div class="form-group">
                    <label class="control-label col-md-3" for="code">Aktivační kód:</label>

                    <div class="col-md-9">
                        <input id="code" name="code" type="text" placeholder="aktivační kód" class="form-control input-md"
                               required="">
                    </div>
                </div>
            </fieldset>

    </div>
    <div class="panel-footer">
        <input type="submit" class="btn btn-primary" value="Aktivovat">
    </div>
</div>
</form>
