<form method="post" class="form-horizontal">
    <div class="panel">
        <div class="panel-heading">
            <h1 class="page-header">Založit nové téma</h1>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label class="col-md-4 control-label" for="topic_subject">Téma:</label>

                <div class="col-md-4">
                    <input id="topic_subject" name="topic_subject" type="text" placeholder="téma..."
                           class="form-control input-md" required="">
                </div>
            </div>
            <div id="mainEditorContainer"></div>
        </div>
        <div class="panel-footer">
            <input type="submit" class="btn btn-sm btn-primary" value="Založit">
        </div>
    </div>
</form>
<script src="js/editorJQ.js"></script>
<script src="js/view/forum-new-topic.js"></script>

