<div class="panel">
    <div class="panel-heading">
        <h1 class="page-header">Forum</h1>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-hover table-striped table-bordered">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Název</th>
                    <th>Témata</th>
                    <th>Příspěvky</th>
                    <th>Poslední příspěvek</th>
                </tr>
                </thead>
                <tbody>
                <? if ($forumCategories) : ?>
                    <? foreach ($forumCategories as $category) : ?>
                        <tr>
                            <td class="text-center"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></td>
                            <td class="forum-item"><h4><a href="forum/show-topics/<?= $category['category_url']; ?>"><?= $category['category_name']; ?></a></h4></td>
                            <td class="text-center"><?= ($category['category_topics_count']) ? $category['category_topics_count'] : "0"; ?></td>
                            <td class="text-center"><?= ($category['topic_posts_count']) ? $category['topic_posts_count'] : 0; ?></td>
                            <td class="text-center">
                                <div class="vcenter">
                                    <a href="forum/show-posts/<?= $category['category_url'] ?>/<?= $category['topic_url'] ?>">Nefunkční</a>
                                </div>
                                <div class="vcenter">
                                    <div class="span12"><?= ($category['nick']) ?: "Nikdo"; ?></div>
                                    <div class="span12"><?= ($category['post_date']) ? app\model\util\DateUtils::formatDateTime($category['post_date']) : ""; ?></div>
                                </div>
                            </td>

                        </tr>
                    <? endforeach ?>
                <? else : ?>
                    <tr>
                        <td>
                            Forum neobsahuje žádná vlákna.
                        </td>
                    </tr>
                <? endif ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <? if ($isAdmin) : ?>

        <? endif ?>
    </div>
</div>
<? if ($isAdmin) : ?>
    <script src="js/manager/forumManager.js"></script>
    <script>
        var forumManager = new ForumManager();
        jQuery(document).ready(function () {
            jQuery(".delete-category").click(function (e) {
                e.preventDefault();
                e.stopPropagation();

                var categoryID = $(this).data("categoryid");

                forumManager.deleteCategory(categoryID, function () {
                    $("#category-" + categoryID).remove();
                });
            });
        });
    </script>
<? endif ?>
