<? use app\model\util\DateUtils;
use app\model\util\MyParsedown; ?>

<ol class="breadcrumb">
    <li><a href="forum">Forum</a></li>
    <li><a href="forum/show-topics/<?= $categoryURL ?>"><?= $categoryName ?></a></li>
    <li class="active"><?= $topicSubject; ?></li>
</ol>

<div class="col-md-12 posts">
    <? if ($_posts) : ?>
        <? $parseDown = new MyParsedown(); ?>
        <? foreach ($_posts as $key => $post) : ?>
            <div class="row forum-post" id="post-<?= $post['post_id'] ?>">
                <? if ($isAdmin) : ?>
                <span class="btn btn-xs btn-danger remove-post" data-postid="<?= $post['post_id'] ?>" style=" position: absolute; right: 10px; z-index: 2;">Smazat</span>
                <? endif ?>
                <div class="col-xs-3 col-sm-2 col-md-1 author">
                    <a href="profile/<?= $post['post_by'] ?>">
                        <img class="img-responsive img-circle center-block user-image" src="uploads/image/avatar/<?= $post['user_avatar'] ?>.png" alt="<?= $post['user_nick']; ?>"/>
                        <p class="nodecoration"><?= $post['user_nick']; ?></p>
                    </a>
                </div>
                <div class="col-xs-9 col-md-10 col-lg-11" style="min-height: 70px;">
                    <?= $parseDown->text($posts[$key]['post_content']); ?>
                </div>
                <span class="small right"><?= DateUtils::prettyDateTime($post['post_date']); ?></span>
            </div>
        <? endforeach ?>
    <? else : ?>
        <div class="forum-item">
            <p>Vlákno neobsahuje žádné příspěvky. Buď první, kdo něco napíše</p>
        </div>
    <? endif ?>
</div>
<hr style="width: 100%;">

<form id="submitForm" method="post" class="form-horizontal">
<div class="panel">
    <div class="panel-heading">
        <h2>Odpověď</h2>
    </div>
    <div class="panel-body">
            <div id="mainEditorContainer"></div>
            <div class="g-recaptcha" data-theme="dark" data-sitekey="6LcN3g0TAAAAAO-4iq4hSU-m24HFNUJBy-n07Xck"></div>
    </div>
    <div class="panel-footer">
        <input type="submit" id="send-post" class="btn btn-sm btn-primary">
    </div>
</div>
</form>

<script src="js/editorJQ.js"></script>
<script src="js/manager/forumManager.js"></script>
<script>
    var socket = io('localhost:8080/forum-posts');

    socket.on('connect', function () {
        socket.emit('join-room', "<?= $topicHash ?>");
    });
</script>
<script src="js/view/forum-posts.js"></script>