<ol class="breadcrumb">
    <li><a href="forum">Forum</a></li>
    <li class="active"><?= $categoryName ?></li>
</ol>

<div style="margin-bottom: 10px;"><span class="btn btn-primary"><a href="forum/new-topic">Nové vlákno</a></span></div>
<? if (isset($topics)) : ?>
    <div class="table-responsive">
        <table class="table table-hover table-bordered">
            <thead>
            <tr>
                <th>#</th>
                <th>Název</th>
                <th>Příspěvky</th>
                <th>Poslední příspěvek</th>
                <? if ($isAdmin) : ?>
                <th>Akce</th>
                <? endif ?>
            </tr>
            </thead>
            <tbody>
            <? foreach ($topics as $topic) : ?>
                <tr id="topic-<?= $topic['topic_id'] ?>">
                    <td><span class="glyphicon glyphicon-book"></span></td>
                    <td>
                        <h4>
                            <a href="forum/show-posts/<?= $categoryUrl; ?>/<?= $topic['topic_url']; ?>"><?= $topic['topic_subject']; ?></a>
                        </h4>
                    </td>
                    <td class="text-center"><?= $topic['topic_posts_count']; ?></td>
                    <td>Undefined</td>
                    <? if ($isAdmin) : ?>
                    <td>
                        <span class="btn btn-xs btn-danger delete-topic" data-topicid="<?= $topic['topic_id'] ?>">Smazat</span>
                    </td>
                    <? endif ?>
                </tr>
            <? endforeach ?>
            </tbody>
        </table>
    </div>
<? else : ?>
    <p>Můžeš založit nové vlákno.</p>
<? endif ?>

<? if ($isAdmin) : ?>
    <script src="js/forumManager.js"></script>
    <script>
        var forumManager = new ForumManager();

        jQuery(".delete-topic").click(function (e) {
            e.preventDefault();
            e.stopPropagation();

            var topicID = $(this).data("topicid");

            forumManager.deleteTopic(topicID, function () {
                $("#topic-" + topicID).remove();
            });
        });
    </script>
<? endif ?>
