<ol class="breadcrumb">
    <li><a href="forum">Forum</a></li>
    <li class="active"><?= $categoryName ?></li>
</ol>
<div class="row">
    <div class="col-md-12">
        <a href="forum/new-topic" class="btn btn-xs btn-primary">Nové téma</a>
    </div>
    <? if (isset($topics)) : ?>
        <div class="col-md-12 voffset2">
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Název</th>
                        <th>Příspěvky</th>
                        <th>Poslední příspěvek</th>
                        <? if ($isAdmin) : ?>
                            <th>Akce</th>
                        <? endif ?>
                    </tr>
                    </thead>
                    <tbody>
                    <? foreach ($topics as $topic) : ?>
                        <tr id="topic-<?= $topic['topic_id'] ?>">
                            <td><span class="glyphicon glyphicon-book"></span></td>
                            <td>
                                <h4>
                                    <a href="forum/show-posts/<?= $categoryUrl; ?>/<?= $topic['topic_url']; ?>"><?= $topic['topic_subject']; ?></a>
                                </h4>
                            </td>
                            <td class="text-center"><?= $topic['topic_posts_count']; ?></td>
                            <td class="text-center"><?= ($topic['last_post_user']) ?: "Nikdo"; ?>
                                <br><?= app\model\util\DateUtils::formatDateTime($topic['last_post_date']); ?></td>
                            <? if ($isAdmin) : ?>
                                <td>
                                    <span class="btn btn-xs btn-danger delete-topic"
                                          data-topicid="<?= $topic['topic_id'] ?>">Smazat</span>
                                </td>
                            <? endif ?>
                        </tr>
                    <? endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>
    <? else : ?>
        <p>Můžeš založit nové vlákno.</p>
    <? endif ?>
</div>
<? if ($isAdmin) : ?>
    <script src="js/manager/forumManager.js"></script>
    <script>
        var forumManager = new ForumManager();
        jQuery(document).ready(function () {
            jQuery(".delete-topic").click(function (e) {
                e.preventDefault();
                e.stopPropagation();

                var topicID = $(this).data("topicid");

                forumManager.deleteTopic(topicID, function () {
                    $("#topic-" + topicID).remove();
                });
            });
        });
    </script>
<? endif ?>
