<ol class="breadcrumb">
    <li><a href="forum">Forum</a></li>
    <li class="active"><?= $categoryName ?></li>
</ol>

<div style="margin-bottom: 10px;"><span class="btn btn-primary"><a href="forum/new-topic">Nové vlákno</a></span></div>
<? if (isset($topics)) : ?>
    <div class="table-responsive">
        <table class="table table-hover table-bordered">
            <thead>
            <tr>
                <th>#</th>
                <th>Název</th>
                <th>Příspěvky</th>
                <th>Poslední příspěvek</th>
            </tr>
            </thead>
            <tbody>
            <? foreach ($topics as $topic) : ?>
                <tr>
                    <td><span class="glyphicon glyphicon-book"></span></td>
                    <td>
                        <h4>
                            <a href="forum/show-posts/<?= $categoryUrl; ?>/<?= $topic['topic_url']; ?>"><?= $topic['topic_subject']; ?></a>
                        </h4>
                    </td>
                    <td class="text-center"><?= $topic['topic_posts_count']; ?></td>
                    <td>Undefined</td>
                </tr>
            <? endforeach ?>
            </tbody>
        </table>
    </div>
<? else : ?>
    <p>Můžeš založit nové vlákno.</p>
<? endif ?>
