<form method="post" class="col-md-offset-2 col-md-8">
    <div class="panel">
        <div class="panel-heading">
            <h1 class="page-header">Přihlášení</h1>
        </div>
        <div class="panel-body">
            <fieldset>
                <div class="form-group">
                    <div class="input-group">
                        <input id="nick" class="form-control" placeholder="Uživatelské jméno" name="nick" type="text">
                        <label for="nick" class="input-group-addon glyphicon glyphicon-user"></label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <input id="password" class="form-control" placeholder="Heslo" name="password" type="password"
                               value="">
                        <label for="password" class="input-group-addon glyphicon glyphicon-lock"></label>
                    </div>
                </div>
                <div class="checkbox">
                    <label>
                        <input name="remember" type="checkbox" value="remember me"> Pamatovat si mě
                    </label>
                </div>

            </fieldset>
        </div>
        <div class="panel-footer">
            <input type="submit" class="btn btn-sm btn-success btn-block" value="Přihlásit">
        </div>
    </div>
</form>
