<form method="post" class="col-md-offset-2 col-md-8">
    <div class="panel">
        <div class="panel-heading">
            <h1 class="page-header">Přihlášení</h1>
        </div>
        <div class="panel-body">
            <fieldset>
                <input type="hidden" name="form-name" value="login-form">

                <div class="form-group">
                    <div class="input-group">
                        <?= $form['email'] ?>
                        <label for="email" class="input-group-addon glyphicon glyphicon-envelope"></label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <?= $form['password'] ?>
                        <label for="password" class="input-group-addon glyphicon glyphicon-lock"></label>
                    </div>
                </div>
                <div class="checkbox col-sm-6">
                    <label>
                        <input name="remember-me" type="checkbox" value="true"> Pamatovat si mě
                    </label>
                </div>
                <div class="col-sm-6 text-right" style="margin-top: 10px">
                    <a href="login/new-password-request">Zapomněl jsi heslo?</a>
                </div>
            </fieldset>
        </div>
        <div class="panel-footer">
            <input type="submit" class="btn btn-sm btn-success btn-block" value="Přihlásit">
        </div>
    </div>
</form>
