<div class="panel">
    <div class="panel-heading">
        <h1 class="page-header">Zprávy</h1>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="hidden-xs col-sm-4 conversation-list">
                a
            </div>
            <? if ($conversations) : ?>
                <? $parsedown = new \app\model\util\MyParsedown() ?>
                <div class="col-xs-12 col-sm-8 messages">
                    <? foreach ($conversations as $key => $conversation) : ?>
                        <div class="col-xs-12 list-item">
                            <div class="col-xs-4 col-sm-2 author">
                                <a href="profile/<?= $conversation['user_id'] ?>">
                                    <img class="img-responsive img-circle center-block user-image"
                                         src="uploads/image/avatar/<?= $conversation['user_avatar'] ?>.png"
                                         alt="<?= $conversation['user_nick'] ?>"/>
                                    <p class="nodecoration"><?= $conversation['user_nick'] ?></p>
                                </a>
                            </div>
                            <div class="col-xs-8 col-sm-10 col-md-10 col-lg-10" style="min-height: 70px;">
                                <a href="messages/conversation/<?= $conversation['conversation_room_hash'] ?>">
                                    <?= $parsedown->text($_conversations[$key]['message_content']) ?>
                                </a>
                            </div>
                            <span
                                class="small right"><?= \app\model\util\DateUtils::prettyDateTime($conversation['message_time']); ?></span>
                        </div>
                    <? endforeach ?>
                </div>
            <? endif ?>
        </div>
    </div>
</div>