<form method="post" class="col-md-offset-2 col-md-8">
    <div class="panel">
        <div class="panel-heading">
            <h1 class="page-header">Žádost o nové heslo</h1>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <div class="input-group">
                    <?= $form['email'] ?>
                    <label for="email" class="input-group-addon glyphicon glyphicon-envelope"></label>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" class="btn btn-sm btn-success btn-block" value="Poslat žádost">
        </div>
    </div>
</form>