<? use app\model\User; ?>
<div class="panel">
    <div class="panel-heading">
        <h1 class="page-header">Profil</h1>
    </div>
    <div class="panel-body">
        <div class="center-block" style="width: 140px;">
            <div class="profile-image dropzone">
                <img src="uploads/image/avatar/<?= /** @var User $user */
                $user['user_avatar'] ?>.png"
                     name="aboutme" width="140" height="140" border="0" class="img-circle user-image">

                <div class="image-overlay"></div>
            </div>
            <h3 class="text-center"><?= $user['user_nick'] ?></h3>
        </div>
        <p class="text-left"><strong>Motto: </strong><br>
            <?= $user['user_motto'] ?></p>
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-md-12">
                <? if ($isLoged) : ?>
                    <? if ($showFriendButton) : ?>
                        <span id="cancel-friend-request" class="btn btn-xs btn-warning <?= (!$isPending) ? 'hidden' : '' ?>"
                              data-friendid="<?= $user['user_id'] ?>"><span
                                class="glyphicon glyphicon-remove-circle"></span> Zrušit žádost</span>
                        <span id="add-to-friend" class="btn btn-xs btn-info <?= ($isFriend) ? 'hidden' : '' ?>"
                              data-friendid="<?= $user['user_id'] ?>"><span
                                class="glyphicon glyphicon-plus"></span> Přidat do přátel</span>
                        <span id="remove-from-friend"
                              class="btn btn-xs btn-danger <?= (!$isFriend) ? 'hidden' : '' ?>"
                              data-friendid="<?= $user['user_id'] ?>"><span
                                class="glyphicon glyphicon-minus"></span> Odebrat z přátel</span>
                    <? endif ?>
                    <span class="btn btn-xs btn-success fileinput-button">
                        <i class="glyphicon glyphicon-upload"></i>
                        <span>Nahrát obrázek...</span>
                        </span>
                    <input id="avatar-upload" type="file" name="avatar-image">
                    <? if ($user['user_role']->valid(USER_ROLE_REDACTOR, false)) : ?>
                        <a href="article-manager"><span class="btn btn-xs btn-info">Správce článků</span></a>
                    <? endif ?>
                    <a href="settings"><span class="btn btn-xs btn-warning">Nastavení</span></a>
                    <a href="favorite-articles" class="btn btn-xs btn-info">Oblíbené články</a>
                    <? if ($user['user_role']->valid(USER_ROLE_ADMIN, false)) : ?>
                        <a href="admin"><span class="btn btn-xs btn-danger right">Administrace</span></a>
                    <? endif ?>
                <? endif ?>
            </div>
        </div>
    </div>
</div>

<script src="js/manager/relationshipsManager.js"></script>
<script src="js/view/profile.js"></script>