<? use app\model\User; ?>
<div class="panel">
    <div class="panel-heading">
        <h1 class="page-header">Profil</h1>
    </div>
    <div class="panel-body">
        <div class="center-block" style="width: 140px;">
            <div class="profile-image dropzone">
                <img src="uploads/image/avatar/<?= /** @var User $user */
                $user['user_avatar'] ?>.png"
                     name="aboutme" width="140" height="140" border="0" class="img-circle user-image">

                <div class="image-overlay"></div>
            </div>
            <h3 class="text-center"><?= $user['user_nick'] ?></h3>
        </div>
        <p class="text-left"><strong>Motto: </strong><br>
            <?= $user['user_motto'] ?></p>
    </div>
    <div class="panel-footer">
        <? if ($isLoged) : ?>
            <span class="btn btn-xs btn-success fileinput-button">
                <i class="glyphicon glyphicon-upload"></i>
                <span>Nahrát obrázek...</span>
            </span>
            <input id="avatar-upload" type="file" name="avatar-image">
            <? if ($user['user_role']->valid(USER_ROLE_REDACTOR, false)) : ?>
                <a href="article-manager"><span class="btn btn-xs btn-info">Správce článků</span></a>
            <? endif ?>
            <a href="settings"><span class="btn btn-xs btn-warning">Nastavení</span></a>
            <a href="favorite-articles" class="btn btn-xs btn-info">Oblíbené články</a>
            <? if ($user['user_role']->valid(USER_ROLE_ADMIN, false)) : ?>
                <a href="admin"><span class="btn btn-xs btn-danger right">Administrace</span></a>
            <? endif ?>
        <? endif ?>
    </div>
</div>

<script>
    var uploader = new CZFXuploader({
        url: "profile/upload/avatar",
        fileName: "avatar",
        callback: function (data) {
            jQuery(".profile-image img").attr("src", data['imgSrc']);
        }
    });
    uploader.init();

    jQuery("#avatar-upload").change(function () {
        uploader.handleFiles(this.files);
    });
</script>