<form method="post" class="col-md-offset-2 col-md-8">
    <input type="hidden" name="form-name" value="register-form">
    <div class="panel">
        <div class="panel-heading">
            <h1 class="page-header">Registrace</h1>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <div class="input-group">
                    <?= $form['username'] ?>
                    <label class="input-group-addon glyphicon glyphicon-user" for="username"></label>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <?= $form['email'] ?>
                    <label class="input-group-addon glyphicon glyphicon-envelope" for="email"></label>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <?= $form['password'] ?>
                    <label class="input-group-addon glyphicon glyphicon-lock" for="password"></label>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <?= $form['password2'] ?>
                    <label class="input-group-addon glyphicon glyphicon-lock" for="passwordAgain"></label>
                </div>
            </div>
            <div class="g-recaptcha" data-theme="dark" data-sitekey="6LcN3g0TAAAAAO-4iq4hSU-m24HFNUJBy-n07Xck"></div>
        </div>
        <div class="panel-footer">
            <input type="submit" class="btn btn-sm btn-success btn-block" value="Zaregistrovat">
        </div>
    </div>
</form>
