<div class="panel">
    <div class="panel-heading">
        <h1 class="page-header">Registrace</h1>
    </div>
    <div class="panel-body">
        <form id="submitForm" method="post" class="col-md-offset-2 col-md-8">
            <div class="form-group">
                <div class="input-group">
                    <input id="username" name="username" type="text" placeholder="Přihlašovací jméno"
                           class="form-control input-md" required="">
                    <label class="input-group-addon glyphicon glyphicon-user" for="username"></label>
                </div>

            </div>
            <div class="form-group">
                <div class="input-group">
                    <input id="email" name="email" type="email" placeholder="E-mail"
                           class="form-control input-md" required="">
                    <label class="input-group-addon glyphicon glyphicon-envelope" for="email"></label>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input id="password" name="password" type="password" placeholder="Heslo"
                           class="form-control input-md" required="">
                    <label class="input-group-addon glyphicon glyphicon-lock" for="password"></label>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input id="passwordAgain" name="passwordAgain" type="password" placeholder="Heslo znovu"
                           class="form-control input-md" required="">
                    <label class="input-group-addon glyphicon glyphicon-lock" for="passwordAgain"></label>
                </div>
            </div>

            <div class="g-recaptcha" data-theme="dark" data-sitekey="6LcN3g0TAAAAAO-4iq4hSU-m24HFNUJBy-n07Xck"></div>
        </form>
    </div>
    <div class="panel-footer">
        <button id="submiter" class="btn btn-lg btn-success btn-block">Zaregistrovat</button>
    </div>
</div>
