<form id="submitForm" method="post" class="form-horizontal">
    <div class="panel">
        <div class="panel-heading">
            <h1 class="page-header">Podpora</h1>
        </div>
        <div class="panel-body">
            <div class="col-md-12">
                <div class="form-group col-md-2">
                    <label class="control-label" for="report_type">Typ zprávy:</label>
                    <select class="form-control" name="report_type" id="report_type" required="">
                        <option value="0">Připomínka</option>
                        <option value="1">Návrh</option>
                        <option value="2">Chyba</option>
                        <option value="3">Pochvala</option>
                    </select>
                </div>
            </div>
            <div class="col-md-12">
                <div id="mainEditorContainer"></div>
            </div>
            <div class="col-md-12">
                <? \app\model\service\CaptchaService::printCaptcha(); ?>
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" class="btn btn-sm btn-primary">
        </div>
    </div>
</form>
<script src="js/editorJQ.js"></script>
<script src="js/view/support.js"></script>

