<form id="submitForm" method="post" class="form-horizontal">
    <div class="panel">
        <div class="panel-heading">
            <h1 class="page-header">Podpora</h1>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label class="col-md-4 control-label" for="name">Uživatelské jméno:</label>

                <div class="col-md-4">
                    <input id="name" name="name" type="text" placeholder="uživatelské jméno"
                           class="form-control input-md" required="">
                </div>
            </div>

            <div id="mainEditorContainer"></div>

            <div class="g-recaptcha" data-theme="dark" data-sitekey="6LcN3g0TAAAAAO-4iq4hSU-m24HFNUJBy-n07Xck"></div>
        </div>
        <div class="panel-footer">
            <input type="submit" class="btn btn-sm btn-primary">
        </div>
    </div>
</form>
<script src="js/editorJQ.js"></script>
<script>
    jQuery(document).ready(function () {

        var buttons = [
            {class: 'bold', before: '**', after: '**', tooltip: 'Tučný'},
            {class: 'italic', before: '*', after: '*', tooltip: 'Kurzíva'},
            {class: 'strikethrough', before: '~~', after: '~~', tooltip: 'Přeškrtnutý'},
            {class: 'code', before: '```\n', after: '\n```', tooltip: 'Vložit kód'},
            {class: 'inline-code', before: '`', after: '`', tooltip: 'Vložit kód do řádku'},
            {class: 'quotes', before: '> ', tooltip: 'Citace'},
            {class: 'ordered-list', before: '1. \n2. \n3. ', after: '', space: -8, tooltip: 'Uspořádaný seznam'},
            {class: 'unordered-list', before: '- \n- \n- ', after: '', space: -6, tooltip: 'Neuspořádaný seznam'},
            {class: 'link', before: '[text]', after: '(odkaz)', space: -5, tooltip: 'Odkaz'}
        ];
        var editor = new EditorJQ(
            '#mainEditorContainer',
            {
                buttons: buttons,
                areaName: 'message'
            });
        editor.init();
    });
</script>

