<div class="panel">
    <div class="panel-heading">
        <h1 class="page-header">Administrace - rozcestník</h1>
    </div>
    <div class="panel-body">
        <? foreach ($pages as $key => $value) : ?>
            <div class="col-sm-6 col-md-4">
                <a href="admin-<?= $key ?>" class="nodecoration">
                    <div class="thumbnail my-thumbnail">
                        <img src="img/<?= $value['img'] ?>.png" alt="<?= $value['img-alt'] ?>">

                        <div class="caption">
                            <h3><?= $value['header'] ?></h3>

                            <p><?= $value['descr'] ?></p>
                        </div>
                    </div>
                </a>
            </div>
        <? endforeach ?>
    </div>
</div>