<ol class="breadcrumb">
    <li><a href="admin">Rozcestník</a></li>
    <li><a href="admin-category-manager">Správce kategorií</a></li>
    <li class="active"><?= !empty($category['category_name'])? $category['category_name'] :"Nová kategorie" ?></li>
</ol>

<form id="form-category-create" method="post" enctype="multipart/form-data">
    <div class="panel">
        <div class="panel-heading">
            <h1 class="page-header"><?= (!empty($category['category_name']) ? "Upravit kategorii" : "Nová kategorie") ?></h1>
        </div>
        <div class="panel-body">
            <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="form-group">
                    <label class="control-label" for="category-id">ID kategorie</label>
                    <input id="category-id" name="category-id" type="text" placeholder="id kategorie"
                           class="form-control input-md"
                           value="<?= $categoryID ?>">
                </div>

                <div class="form-group">
                    <label class="control-label" for="category-name">Název kategorie</label>
                    <input id="category-name" name="category-name" type="text" placeholder="název kategorie"
                           class="form-control input-md"
                           required="" value="<?= $category['category_name'] ?>">
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="form-group">
                    <label class=" control-label" for="category-url">URL kategorie:</label>
                    <input id="category-url" name="category-url" type="text" placeholder="url kategorie"
                           class="form-control input-md"
                           required="" value="<?= $category['category_url'] ?>">
                </div>

                <div class="form-group">
                    <label class="control-label" for="categoryparent">Rodičovská kategorie:</label>
                    <select id="category-parent" name="category-parent" class="form-control">
                        <? if ($category['category_parent'] == -1) : ?>
                            <option value="-1">Žádná...</option>
                        <? else : ?>
                            <option
                                value="<?= $category['category_parent']; ?>"><?= $parent['category_name']; ?></option>
                            <option value="-1">Žádná...</option>
                        <? endif ?>
                        <? foreach ($categories as $cat) : ?>
                            <option value="<?= $cat['category_id']; ?>"><?= $cat['category_name']; ?></option>
                        <? endforeach ?>
                    </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="form-group">
                    <label class="control-label" for="category-has-subcats">Obsahuje podkategorie:</label>
                    <input id="category-has-subcats" type="checkbox" name="category-has-subcats"
                           class="form-control input-md boot-switch"
                           <?= ($category['category_has_subcats']) ? 'checked' : '' ?>/>
                </div>

                <div class="form-group">
                    <label class="control-label" for="category-description">Popis categorie:</label>
                    <textarea class="form-control" name="category-description" id="category-description"
                              placeholder="Popis..."
                              required=""><?= $category['category_description'] ?></textarea>
                </div>
            </div>
            <div class="col-xs-12">
                <div class="form-group">
                    <label for="">Obrázek kategorie</label>
                    <div>
                        <span id="category-image-button" class="btn btn-default fileinput-button">Vybrat...</span>
                        <input type="file" id="category-icon-input" name="category-image" style="display: none;">
                        <img id="category-image" src="uploads/image/category/<?= ($category['category_image']) ?>.png" alt="Ikona kategorie" width="100px">
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" class="btn btn-xs btn-primary" value="<?= ($action == "new")? "Vytvořit" : "Upravit" ?>">
            <a href="admin-category-manager" class="btn btn-xs btn-warning right">Zrušit</a>
        </div>
    </div>
</form>

<script src="js/manager/categoryManager.js"></script>
<script src="js/view/admin/category.js"></script>