<ol class="breadcrumb">
    <li><a href="admin">Rozcestník</a></li>
    <li class="active">Správce fora</li>
</ol>

<div class="panel">
    <div class="panel-heading">
        <h1 class="page-header">Správce fora</h1>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-hover table-bordered">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Název</th>
                    <th>URL</th>
                    <th>Akce</th>
                </tr>
                </thead>
                <tbody>
                <? foreach ($forumCategories as $category) : ?>
                    <tr id="category_<?= $category['category_id'] ?>">
                        <td><?= $category['category_id'] ?></td>
                        <td><?= $category['category_name'] ?></td>
                        <td><?= $category['category_url'] ?></td>
                        <td>
                            <a href="/admin-forum-manager/update/<?= $category['category_id'] ?>" class="btn btn-xs btn-default">Upravit</a>
                            <button data-categoryid="<?= $category['category_id'] ?>" class="btn btn-xs btn-danger cat-remove">Odebrat</button>
                        </td>
                    </tr>
                <? endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <a href="admin-forum-manager/new/category" class="btn btn-xs btn-primary">Založit novou kategorii</a>
    </div>
</div>