<ol class="breadcrumb">
    <li><a href="admin">Rozcestník</a></li>
    <li class="active">Nastavení</li>
</ol>

<div class="panel">
    <div class="panel-heading">
        <h1 class="page-header">Nastavení</h1>
    </div>
    <div class="panel-body">
        <? foreach ((array)$values as $key => $value) : ?>
            <? $value = (array)$value ?>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <label for="<?= $key ?>"><?= $value['name'] ?></label>
                <input type="<?= $value['type'] ?>" class="form-control config-item" name="<?= $key ?>" value="<?= $value['key'] ?>">
            </div>
        <? endforeach ?>
    </div>
    <div class="panel-footer">
        <span class="btn btn-xs btn-danger set-as-default">Nastavit jako výchozí</span>
    </div>
</div>

<script src="js/manager/settingsManager.js"></script>
<script src="js/view/admin/settings.js"></script>