<ol class="breadcrumb">
    <li><a href="admin-dashboard">Rozcestník</a></li>
    <li class="active">Nastavení</li>
</ol>

<div class="panel">
    <div class="panel-heading">
        <h1 class="page-header">Nastavení</h1>
    </div>
    <div class="panel-body">
        <? foreach ((array)$values as $key => $value) : ?>
            <? $value = (array)$value ?>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <label for="<?= $key ?>"><?= $value['name'] ?></label>
                <input type="<?= $value['type'] ?>" class="form-control" name="<?= $key ?>" value="<?= $value['key'] ?>">
            </div>
        <? endforeach ?>
    </div>
</div>

<script type="text/javascript" src="js/settingsManager.js"></script>
<script type="text/javascript">

    var m = new SettingsManager();

    jQuery(document).ready(function () {
        jQuery(".form-control").keyup(function (e) {
            if (e.keyCode == 13) {
                var name = $(this).attr("name");
                var val  = $(this).val();

                m.update(name, val);
            }
        })
    });
</script>